Add Support for signatures on the G2 curve for BDN
drand/kyber pull request #53
Opened 2024-01-30 16:29 UTC by matejpavlovic

Feel free to further edit the code in this PR, in particular adding proper tests.

2024-02-07 18:21 UTC, AnomalRoil requested changes

2024-02-07 21:54 UTC, matejpavlovic commented on sign/bdn/bdn.go
> +func AggregateSignatures(scheme *Scheme, sigs [][]byte, mask *sign.Mask) (kyber.Point, error) {
I wanted to minimize the changes to the structure of the code as much as possible, so I just changed the name and type of the (already existing) function parameter. But it also makes sense to have those functions as methods of `Scheme`. New version ready for review.

2024-02-07 21:57 UTC, matejpavlovic commented
I would also like to mention that my understanding of the code is still rather superficial. This shows, for example, that I did not manage to generalize the unit tests. Please make sure that the code actually works before merging. Thanks!

2024-03-04 14:20 UTC, Kubuxu commented
Hey @AnomalRoil let me know what needs to get done to get this merged.

2024-03-05 06:32 UTC, AnomalRoil commented
It needs more tests I guess, which has been on my to-do for like 2 months 😅

2024-03-06 16:47 UTC, Kubuxu commented
While working on more tests, I discovered that `hashToPoint` is not implemented on bn256 G2 Point.
See the PR to upstream kyber: https://github.com/dedis/kyber/pull/428/files

This is not an issue with bls12381 we are using.

2024-03-06 17:17 UTC, Kubuxu commented
Pull in https://github.com/Kubuxu/kyber/commit/c5d6a111d0149c40c0c845a7033c313666dd0a5c for additional tests

2024-03-08 22:29 UTC, AnomalRoil commented
I just need to  add some retro-compat functions to avoid breaking public APIs and I'll release a new minor release with this 👍🏻

2024-03-08 22:47 UTC, merged